dataset_root_path: /home/cs/OT-diffusion-flow/dataset/data
image_size:
- 218
- 178
channels: 3
latent_dim: 100
batch_size: 64
learning_rate: 0.001
epochs: 3
beta_kld: 1.0
save_epoch_freq: 1
ot_map_params:
  max_iter: 500
  lr: 0.01
  bat_size_n: 1024
vae_encoder_path: OT-flow/saved_models/vae_YYYYMMDD-HHMMSS/vae_final.pth
ot_solver_save_path: OT-flow/saved_models/ot_solver_state_test_run.pth
